....
....
    'default' => env('DB_CONNECTION', 'mysql'),
    //'default' => env('DB_CONNECTION', 'mongodb'),
....
....
    'connections' => [
....
....
        'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('MONGO_HOST'),
            'port'     => env('MONGO_PORT'),
            'database' => env('MONGO_DATABASE'),
            'username' => env('MONGO_USERNAME'),
            'password' => env('MONGO_PASSWORD'),
            'options'  => [
                'database' => env('MONGO_AUTH_DATABASE')
            ]
        ],
....
....
