name: Docker Image Push and ECR Push

on:
  push:
    branches:
      - master # Change this to the desired branch

jobs:
  push-and-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-image .
        docker push your-docker-image

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to Amazon ECR
      run: |
        docker tag your-docker-image:latest <your-aws-account-id>.dkr.ecr.<your-region>.amazonaws.com/your-ecr-repo:latest
        docker push <your-aws-account-id>.dkr.ecr.<your-region>.amazonaws.com/your-ecr-repo:latest
