name: Deploy to ECR

on:
 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: maneeshgs07
        IMAGE_TAG: latest
      run: |
       #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            #   docker build -t docker .
       # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
       docker build -t docker .
        docker tag docker:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

##Deploy to ec2 server###


      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        PRIVATE_KEY: ${{ secrets.AWS_SECRET_KEY  }}
        HOSTNAME : ec2-65-2-30-32.ap-south-1.compute.amazonaws.com
        USER_NAME : ec2-user
            
        
          

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

   # - name: Login to Amazon ECR
    #  id: login-ecr
     # uses: aws-actions/amazon-ecr-login@v1
      
    - name: Pull Docker Compose configuration
      run: |
 
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
        sudo mkdir -p /app
        sudo chown $USER:$USER /app
        cd /app
        git clone https://github.com/maneeshgs/TestMaster.git
        
    - name: Deploy Docker Compose
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: maneeshgs07
        IMAGE_TAG: latest
      run: |
        cd /app/TestMaster
        docker-compose pull
        docker-compose up -d
        
 
          
           




